# Generated by Django 5.0 on 2024-01-22 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_postmodel_title_alter_postmodel_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dislikepost',
            name='is_dislike',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='likepost',
            name='is_like',
            field=models.BooleanField(default=False),
        ),
    ]
