# Generated by Django 5.0 on 2024-01-23 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_comment_user_dislikepost_is_dislike_likepost_is_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='comment',
            field=models.IntegerField(default=0),
        ),
    ]
